Resources:
  CustomerFridgeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "userId"
          "AttributeType": "S"
        - "AttributeName": "name"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "userId"
          "KeyType": "HASH"
        - "AttributeName": "name"
          "KeyType": "RANGE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "FridgeItems"