Resources:
  SavedRecipesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "userId"
          "AttributeType": "S"
        - "AttributeName": "recipeId"
          "AttributeType": "N"
      "KeySchema":
        - "AttributeName": "userId"
          "KeyType": "HASH"
        - "AttributeName": "recipeId"
          "KeyType": "RANGE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "SavedRecipes"